[package]
name = "warp_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "=0.3.7"
tokio = { version = "=1.45.1", features = ["full"] }
reqwest = { version = "=0.12.19", features = ["json"] }
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = "=1.0.140"
bytes = "=1.10.1"
