services:
  cockroachdb:
    image: cockroachdb/cockroach:v25.2.0
    hostname: cockroachdb
    container_name: cockroachdb
    ports:
      - '26257:26257'
      - '8080:8080'
    command: start-single-node --insecure
