[package]
name = "reverse-proxy-actix"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
actix-web = "=4.11.0"
reqwest = { version = "=0.12.19", features = ["json"] }
tokio = { version = "=1.45.1", features = ["full"] }
